project:
  type: website
  resources:
    - figures/gecco_ecip_2025



website:
  title: "Gecco: ECiP"
  description: "Evolutionary Computation in Practice (ECiP) track at GECCO - Bridging Academia and Industry."
  site-url: "https://sequential-parameter-optimization.github.io/evolutionary-computation-in-practice/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - reference.qmd
    right:
      - icon: github
        href: https://github.com/sequential-parameter-optimization/evolutionary-computation-in-practice
  open-graph:
    title: "Gecco: Evolutionary Computation in Practice"
    description: "Bridging Academia and Industry in Evolutionary Computation"
    image: https://gecco-2026.sigevo.org/dl214
  twitter-card:
    card-style: summary_large_image
    creator: "@GeccoConf"

format:
  html:
    theme:
      - superhero
    css: styles.css
    toc: true
    number-sections: false
    smooth-scroll: true

execute:
  freeze: auto
