project:
  type: website
  output-dir: _site

website:
  title: "Gecco: Evolutionary Computation in Practice"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/sequential-parameter-optimization/evolutionary-computation-in-practice

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    number-sections: true

execute:
  freeze: auto

